### PR TITLE
Allow AnsiUp to take a custom/user-defined formatter for ANSI output

### PR DESCRIPTION
**Pull request by marques-work**
Introduce public function  `ansi_to(text, formatter)` to separate the parsing of text/sequences from the output generation logic so that one can implement custom formatters.

  - introduce 2 new interfaces: `TextWithData` and `Formatter`
    - `TextWithData` wraps a text fragment with a snapshot of the `AnsiUp` state (`fg`, `bg`, `bright`), and represents a unit of work provided to a `Formatter` to transform into output.
      ```typescript
      interface TextWithData {
        fg: AU_Color;
        bg: AU_Color;
        bright: boolean;
        text: string;
      }
      ```
    - `Formatter` is an interface with 2 functions:
      ```typescript
      interface Formatter {
        // receives a TextWithData and an AnsiUp instance (so that a Formatter can access settings and the ansi palette)
        transform(fragment: TextWithData, instance: AnsiUp): any,

        // receives a set of outputs from transform and composes a final result; also receives an AnsiUp instance so settings and palette are accessible
        compose(segments: any[], instance: AnsiUp): any
      }
      ```
  - AnsiUp instances have 2 predefined formatters: `htmlFormatter` and `textFormatter`
  - `ansi_to_html()` and `ansi_to_text()` are now syntactic sugar to wrap `ansi_to(text, htmlFormatter)` and `ansi_to(text, textFormatter)` respectively

### CODE REVIEW

**Comment by marques-work** [comment]
Wanted to add some context as to why I made this PR:

I'm working on an open-source build automation tool, and we are using `AnsiUp` to render colored console output. For very large sets of text (as one can expect from the console output generated by builds), the browser was spending lots of time parsing HTML that made the user experience nearly intolerable -- this wasn't the only factor causing performance issues, but it was a major/significant one. We improved performance nearly five-fold alone by hacking AnsiUp to instead return an array of Element instances using [crel](https://github.com/KoryNunn/crel).

Naturally, we don't want to heavily customize an actively maintained library with an incompatible change with no clear upgrade path, so I wrote this PR to serve as a generic/abstract solution to be contributed back upstream. This change allows AnsiUp to keep its original API while accommodating our customizations (it would now be trivial to extract our customizations into a `Formatter` object). This abstraction would allow AnsiUp users to now output whatever they need (e.g. React components, etc) instead of having to work with raw markup.

Please, let me know what you think.

**Comment by marques-work** [comment]
@drudru any thoughts on this change?

**Comment by drudru** [comment]
Hello - will reply tomorrow. sorry for delay

**Comment by marques-work** [comment]
@drudru no problem, thank you for taking a look!

**Comment by drudru** [comment]
I think this is cool. I like the idea of allowing customizations like this, yet keeping the existing behaviour as a default.

**Comment by drudru** [comment]
Hi, I tried to dig into all of the changes in the .ts file, but there are a lot.

I noticed a lot of small syntax changes like: added braces, transforming octal, triple ===, etc.
Were you using a tool to perform some of these changes? Did those generate warnings?

I need to figure out how to get the code side by side on my own desktop vs. trying to read this on github.

**Comment by marques-work** [comment]
@drudru I think I used jshint on the generated JS file; most of the warnings were that strong equality was preferred here, which is usually a good practice anyway unless you intentionally want to allow type coercion before comparison. Minor point, admittedly, but I do frequently run with a linter for good measure. The other significant, but minor change was adding "use strict", which forbids the use of octal sequences; that's why you see me changing the octal sequence `\033' to the hex sequence '\x1B`.

Yeah, there were a lot of changes; sorry about that. Here's how you could diff the two locally:

```bash
git remote add marques-work https://github.com/marques-work/ansi_up
git fetch marques-work

# compare the tip of my branch to your master and
# ignore whitespace-only changes; makes it easier to diff
git diff -w master marques-work/allow-custom-outputter -- ansi_up.ts
```

Feel free to ask me anything else about the implementation.

Thanks!

Marques

**Comment by drudru** [comment]
Very cool - the "use strict" and linting are good things. I will have time tomorrow to do the review.

**Comment by marques-work** [comment]
Cool, looking forward to it.

**Comment by drudru** [comment]
Ok - doing this now...

**Comment by drudru** [comment]
Hi - thanks for your help with this. I like the linting and structure.

One thing I would prefer is to keep the old comment and regex back with the block.match.

The only other thing I thought of as a nice to have would be a simple test of the ansi_to() method. However, I cannot myself think of worthy test.

So, other than the regex, everything looks great.

BTW, I tried 'git difftool' instead and it opened FileMerge (XCode). It made the job quite a bit easier.

Thank you.

**Comment by marques-work** [comment]
@drudru Great, glad to hear. I can move the SGR_REGEX back to where it was; the only caveat is that it is rebuilt each time with process_ansi(), yet it never changes. That was mainly why I moved it to the top as a const. For our application, this could be called thousands of times, so I am not sure if the performance impact of regenerating the regex is significant or not. I may do some profiling on this, but for now, here is the requested change.

**Comment by marques-work** [comment]
@drudru actually, as a pretty simple fix to address any performance concerns, I resorted to lazy-initializing the regex as an instance variable.

**Comment by drudru** [comment]
Hi - thanks. Actually, it was lazy-initializing before - it only built it once - so all good. I do actually like where you put the regex comment. That makes more sense.

So - this is all set. I will merge, bump the semantic version, and the Readme later.

Thanks for your contribution! 👍

**Comment by marques-work** [comment]
@drudru sure thing :). I did add a test for `ansi_to()` in https://github.com/drudru/ansi_up/pull/37 for good measure.

**Pull request merged**
