### PR TITLE
Conversion of ansi_up to ES6 Module Format

### PR DESCRIPTION
**Pull request by Shaun-Regenbaum**
I converted ansi_up.js from CommonJS module format to ESM format, with the change in file extension from .js to .mjs to clearly denote that this is an ESM. This should clear up any errors such as "unexpected export token" when trying to import ansi_up into newer projects. 

Just to be safe, I also added "type":"module" to package.json to let importers know that all .js files should be interpreted as ES6 modules, rather than CJS. You don't technically need both, and this will actually eliminate your ability to use .cjs and .mjs files in the same project, but I think that is bad practice in general. This just ensure that if you do add any files in the future and they are just .js, they should be interpreted correctly.

I feel that it is important to align with modern JavaScript development practices. This should improve ansi_up's integration with static analysis tools and general tooling support. ECMAScript Modules provide benefits such as static imports and exports, and improved performance due to predictable module structure and the ability for bundlers and minifiers to perform "tree shaking" (eliminating unused code).

I doubt this will be the case, but you might need to updated your build and testing environments, as well as your Node version, to ensure compatibility with the ESM format.

### CODE REVIEW

**Comment by Shaun-Regenbaum** [comment]
If you have any questions or anything, let me know and I'd be glad to help out. Thanks for your work!

**Comment by Shaun-Regenbaum** [comment]
#80 Also, this should resolve this issue, so hopefully you can close that while you are at it.

**Comment by silverwind** [comment]
I think at minimum, the AMD wrapper should be removed. It has no place in a ESM module.

**Comment by Shaun-Regenbaum** [comment]
I mean that's a nice to have, but it doesn't actually change anything...

**Comment by drudru** [comment]
Thanks :+1:  I am looking at this now.

**Comment by drudru** [comment]
Wow - this is a nice surprise. I created a branch and tried using the latest Typescript compiler.
I had to make a bunch of changes, and in the end, couldn't get it to compile correctly.
Your changes are minimal. This is great.
I need to test this out. If all goes well (and it should), I will merge this soon.
This will allow people on the 5.x to have this fix without the big changes I had lined up.

**Comment by drudru** [comment]
> I think at minimum, the AMD wrapper and the globals contained within should be removed. Such a wrapper has no place in a ESM module.

Agreed, that will go away in 6.x.

**Comment by Shaun-Regenbaum** [comment]
I started a proper move to ES6 format. Will upload later.

**Review by Shaun-Regenbaum — COMMENTED** [review]
I made more permanent change to make it a proper ES6 module. I know it looks like a lot changed, but I just changed formats.

**Comment by Shaun-Regenbaum** [comment]
I personally tried this in my own project (published a new npm package called ansi-up-402) and it seems to work properly. Let me know how else I can help!

**Comment by drudru** [comment]
Hi @Shaun-Regenbaum - thanks for your help.
The new stuff is too big of a change.
We need to do that in a separate pull. (More on that later)

Here is how I would like to proceed.
The first submission is pretty close.

The goal is to put out a 5.3 release.
That means that it doesn't break existing deployments.
Therefore, we just add a copy of the file as .mjs.
You will need to change the Makefile to create this.
I will also need additions to the README to show the  new import style for browsers.

That leads to the bigger changes in your second request.
I looked at the commits and it looks like you did those by hand.
This will have to be a separate pull for the 6.x release.
The commit should use the newer Typescript release to generate the ES6 compatible module.

Side note: I will be removing the .vscode directory in the next release.
#85 

Let me know your thoughts on this.
Again, thanks.

**Comment by drudru** [comment]
@Shaun-Regenbaum - ok - so I did the testing.
Just renaming to an .mjs doesn't allow the module to be imported into a browser.
I suspect converting to an ES6 module is the right step.
Can you import the existing ansiup.js into a browser using import AnsiUp from './ansi_up.mjs' ?

**Comment by Shaun-Regenbaum** [comment]
I will look into this next week.

**Comment by drudru** [comment]
Hi - I worked a tiny bit on this today.
I was able to generate the code as an ES6 module.
I am putting that on a separate branch.

Thanks for your pull request, but I'm going to go with the other branch.

**Pull request closed without merging**
