### PR TITLE
Add metadata about typings in package.json

### PR DESCRIPTION
**Pull request by vidartf**
See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

### CODE REVIEW

**Comment by vidartf** [comment]
> Also, if they have the actual .ts file in the npm... would that work better?

Typings files are preferred, as a TS file will be recompiled, possibly with a different version of the compiler or with different settings. If this distributed TS file is the cause of a compile error, you'll be stuck.

**Comment by vidartf** [comment]
> Is this how typings are distributed?

The link included is as close to authoritative guide as you will get for how to publish typings.

**Comment by drudru** [comment]
Thanks for your patience with this.

**Comment by drudru** [comment]
I will push this as a new npm now.

**Pull request merged**
