### PR TITLE
Add option to open links in a new tab

### PR DESCRIPTION
**Pull request by dannytatom**

### CODE REVIEW

**Comment by drudru** [comment]
Thanks - holding off until I land the TypeScript branch.

**Comment by dannytatom** [comment]
aah, didn't notice that. fair enough. thanks for the project. 💃

**Comment by drudru** [comment]
Believe me, you did nothing wrong. My bad for letting that sit too long.

**Comment by drudru** [comment]
Ok - I will let you know soon when I need you to retry. Thanks.

**Comment by drudru** [comment]
Hi - sorry for the late notice, but you could retry now. Thanks.

**Comment by drudru** [comment]
Hi -  I removed the linking option because of the edge cases that people could run into.

**Pull request closed without merging**
